import { Transaction } from "@/types/transaction";

export const transactions: Transaction[] = [
  {
    id: "1",
    amount: 5000,
    type: "revenue",
    date: "2025-01-10",
    status: "paid",
    customer: "Acme Corp",
  },
  {
    id: "2",
    amount: 1200,
    type: "expense",
    date: "2025-01-12",
    status: "paid",
    customer: "Office Supplies",
  },
  {
    id: "3",
    amount: 7000,
    type: "revenue",
    date: "2025-02-05",
    status: "paid",
    customer: "Tech Startup Inc",
  },
  {
    id: "4",
    amount: 2000,
    type: "expense",
    date: "2025-02-08",
    status: "paid",
    customer: "Software License",
  },
  {
    id: "5",
    amount: 9000,
    type: "revenue",
    date: "2025-03-02",
    status: "paid",
    customer: "Global Solutions",
  },
  {
    id: "6",
    amount: 3500,
    type: "expense",
    date: "2025-03-11",
    status: "paid",
    customer: "Cloud Services",
  },
  {
    id: "7",
    amount: 6000,
    type: "revenue",
    date: "2025-04-07",
    status: "paid",
    customer: "Digital Media LLC",
  },
  {
    id: "8",
    amount: 3500,
    type: "expense",
    date: "2025-04-17",
    status: "paid",
    customer: "Marketing",
  },
  {
    id: "9",
    amount: 10000,
    type: "revenue",
    date: "2025-05-19",
    status: "paid",
    customer: "Enterprise Co",
  },
  {
    id: "10",
    amount: 4000,
    type: "expense",
    date: "2025-05-27",
    status: "paid",
    customer: "Team Salaries",
  },
  {
    id: "11",
    amount: 8500,
    type: "revenue",
    date: "2026-03-05",
    status: "paid",
    customer: "Innovation Labs",
  },
  {
    id: "12",
    amount: 2800,
    type: "expense",
    date: "2026-03-08",
    status: "paid",
    customer: "utilities",
  },
  {
    id: "13",
    amount: 12000,
    type: "revenue",
    date: "2026-03-15",
    status: "paid",
    customer: "Future Systems",
  },
  {
    id: "14",
    amount: 5200,
    type: "expense",
    date: "2026-03-18",
    status: "paid",
    customer: "Equipment",
  },
  {
    id: "15",
    amount: 7500,
    type: "revenue",
    date: "2026-03-25",
    status: "paid",
    customer: "Creative Agency",
  },
];

export const salesOrders = [
  {
    id: "ORD-001",
    customer: "John Doe",
    email: "john@acmecorp.com",
    product: "Pro Plan",
    amount: 299,
    status: "completed",
    date: "2026-03-28",
  },
  {
    id: "ORD-002",
    customer: "Jane Smith",
    email: "jane@techstartup.com",
    product: "Starter Plan",
    amount: 99,
    status: "completed",
    date: "2026-03-28",
  },
  {
    id: "ORD-003",
    customer: "Alex Johnson",
    email: "alex@globalsolutions.com",
    product: "Enterprise Plan",
    amount: 999,
    status: "completed",
    date: "2026-03-27",
  },
  {
    id: "ORD-004",
    customer: "Sarah Williams",
    email: "sarah@digitalmedia.com",
    product: "Pro Plan",
    amount: 299,
    status: "pending",
    date: "2026-03-26",
  },
  {
    id: "ORD-005",
    customer: "Michael Chen",
    email: "m.chen@innovation.com",
    product: "Starter Plan",
    amount: 99,
    status: "completed",
    date: "2026-03-25",
  },
  {
    id: "ORD-006",
    customer: "Emma Davis",
    email: "emma@futuresystems.com",
    product: "Pro Plan",
    amount: 299,
    status: "failed",
    date: "2026-03-24",
  },
  {
    id: "ORD-007",
    customer: "David Brown",
    email: "d.brown@creativeagency.com",
    product: "Enterprise Plan",
    amount: 999,
    status: "completed",
    date: "2026-03-23",
  },
];

export const monthlyData = [
  { month: "January", revenue: 12500, expenses: 4200, orders: 15 },
  { month: "February", revenue: 16000, expenses: 5100, orders: 22 },
  { month: "March", revenue: 27000, expenses: 11500, orders: 35 },
  { month: "April", revenue: 9500, expenses: 3500, orders: 12 },
  { month: "May", revenue: 14000, expenses: 4000, orders: 18 },
];
